services:
  ranger-build:
    build:
      context: .
      dockerfile: ./ranger-build/Dockerfile
    environment:
      REVISION: '72f6c57'
    user: "1000:1000"
    volumes:
      - ./build-src:/build-src
      - /tmp/.m2:/root/.m2
    command:
      - bash
      - -c
      - |
        cd /build-src
        RUN git clone https://github.com/apache/ranger.git
        cd ranger
        git checkout ${REVISION}
        mvn -T $(proc)C package -DskipTests
