services:
  ranger-build:
    container_name: ranger-build
    build:
      context: ../
      dockerfile: ./ranger-build/Dockerfile
    environment:
      MAVEN_OPTS: -Dmaven.repo.local=/tmp/.m2
      HOME: /tmp
      BUILD_USER: ${BUILD_USER}
      PARALLEL: ${PARALLEL}
    env_file:
      - .env
    volumes:
      - ../build-src:/build-src:rw
      - ${M2_CACHE}:/tmp/.m2
      - ./clone-n-build.sh:/usr/local/bin/clone-n-build.sh
    command:
      - bash
      - -c
      - |
          useradd -u ${BUILD_USER} -m -s /bin/bash build 
          su -c
          su build -c "clone-n-build.sh"
