services:
  postgres:
    image: docker.io/bitnami/postgresql:16.3.0
    environment:
      - POSTGRESQL_PASSWORD=postgres123AA
    volumes:
      - ranger-postgres:/bitnami/postgresql:rw
    networks:
      - ranger
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - node.name=es01
      - cluster.name=es
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ranger-elasticsearch:/usr/share/elasticsearch/data:rw,Z
    networks:
      - ranger

  ranger:
    image: hienphdev/ranger-admin:${VERSION}-${REVISION}
    container_name: ranger
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - ranger
    ports:
      - "6080:6080"
    command:
      - /home/ranger/scripts/ranger.sh
    volumes:
      - ./configs/ranger-admin-install.properties:/opt/ranger/admin/install.properties:Z,ro

  ranger-usersync:
    image: hienphdev/ranger-usersync:${VERSION}-${REVISION}
    container_name: ranger-usersync
    networks:
      - ranger
    volumes:
      - ./configs/ranger-usersync-install.properties:/opt/ranger/usersync/install.properties:Z,ro
    depends_on:
      ranger:
        condition: service_started
volumes:
  ranger-postgres:
  ranger-elasticsearch:
networks:
  ranger:

