name: Relase Build
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: apache/ranger
          ref: 'master'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.x
          cache: npm
          cache-dependency-path: security-admin/src/main/webapp/package-lock.json

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: git checkout 72f6c57
        name: checkout commit

      - run: mvn -DskipTests package
        name: build
